FROM centos:8

# Fix issues with overlayfs
RUN yum clean all
RUN rm -f /var/lib/rpm/__db*
RUN yum clean all
RUN yum install -y yum-plugin-ovl || :
RUN yum install -y yum-utils

RUN yum -y update

# Install buildah
RUN yum -y install buildah crun

CMD /bin/bash
